
title: Networking and Security Research Group
description: >
  The Networking and Security Research Group at the the University of Colorado, led
  by Eric Keller, Sangtae Ha, and Eric Wustrow, is researching all things having to do with the
  networked systems of modern and future infrastructures. We look at the
  security, reliability, performance, etc. of networked infrastructures such as
  data centers, enterprises, and even smart grids - basically anything with a
  communication network.

baseurl: ""
url: "http://nsr-colorado.github.io"

main_nav:
  - text: people
    url: /people/
  - text: about
    url: /about/
  - text: research
    url: /research/
  - text: publications
    url: /publications/

markdown: kramdown

gems:
  - jekyll-redirect-from
